### ISSUE TITLE
Paste images from clipboard

### ISSUE THREAD

**Issue by dandv** [bustlelabs/content-kit-editor#101]
I see in [the demo](http://bustlelabs.github.io/content-kit-editor/demo/) that there is provision for uploading images (though it errors out right now). Any plans to allow pasting images directly from the clipboard, like on Imgur, Slack, Google Docs, GitHub etc?

I'm [comparing WYSIWYG editors](https://github.com/iDoRecall/comparisons/blob/master/JavaScript-WYSIWYG-editors.md) and have been looking for this feature.

**Comment by mixonic** [comment]
Howdy @dandv.

I think it is unlikely that Content-Kit core will ever include a full drag-drop image experience, though I'm not against the included image card having drag-drop.

However it seems this would be something we want a UI library wrapping Content-Kit, or just a shared Content-Kit card, to do (see http://madhatted.com/2015/8/25/content-kit-programmatic-editing). Definitely not included here today. Let me know if I can answer any other questions.
