### ISSUE TITLE
Events on card elements should not intercepted by the editor

### ISSUE THREAD

**Issue by dtetto** [bustlelabs/content-kit-editor#114]
When editing a card within its `element` (say, typing in an injected `textarea` or `input`) the editor’s behavior intercepts and prevents events like backspacing and pasting. The editor’s callbacks don’t need to fire while using in-card UI, and DOM events within the card should not be prevented/intercepted (maybe no DOM events should bubble out of the card element by default?).

**Comment by bantic** [comment]
Ah, yeah, thanks for reporting. I recently refactored the listener code (in #113) to flow through a single [event handling function](https://github.com/bustlelabs/content-kit-editor/blob/master/src/js/editor/editor.js#L563-L567), which should make it easier to stop all event handling when the user is in a sub-UI like a card. This should be straightforward to fix.
