### ISSUE TITLE
un-exec toolbar button fails when selection starts with single-char marker

### ISSUE THREAD

**Issue by bantic** [bustlelabs/content-kit-editor#121]
to reproduce:
  * create a section with text "abc"
  * make "b" bold
  * select "bc", bold button on toolbar should be active, click it to unbold the selection
  * the "b" in the selections does not get unbolded

**Comment by mixonic** [comment]
I believe the toolbar buttons should be going away entirely, and be supplanted by ember components in an addon.

**Comment by bantic** [comment]
Yeah, this is a bug in the editor itself, it's just most easily reproduced using the toolbar.
