### ISSUE TITLE
RFC - Fully custom keyboard events

### ISSUE THREAD

**Issue by rlivsey** [bustlelabs/content-kit-editor#168]
Building on #167 and discussions with @mixonic I thought I'd jot my thoughts down here before getting too far down the rabbit hole with more pull requests.

We're in the process of integrating ember-content-kit in our app and have a few use-cases around keyboard event handling which aren't currently easily supported. For example, overriding enter and preventing a new-line being inserted (eg for comment submission fields), custom behaviour on tab etc...

Pull request #167 goes someway towards supporting this to allow registering arbitrary key commands (previously a modifier key had to be held down & the key pressed be a printable character).

[Currently][1] all internal event handling on `handleKeyDown` happens before calling custom key commands, which means we can't currently override things like delete/enter. 

```js
handleKeydown(event) {
  const key = Key.fromEvent(event);

  if (key.isDelete()) {
    this.handleDeletion(event);
    event.preventDefault();
  } else if (key.isEnter()) {
    this.handleNewline(event);
  } else if (key.isPrintable()) {
    // ...
  }

  this.handleExpansion(event);
  
  // can't handle 'enter' here as it's already happened
  this.handleKeyCommand(event);
}
```

Also, in `handleKeyCommand` `event.preventDefault` is [always called][2] so there can be no conditional handling in the command itself.

## Handle key commands first

I propose moving `handleKeyCommand` to happen before the internal behaviour, and if a command is handled then return at that point:

```js
handleKeydown(event) {
  const key = Key.fromEvent(event);

  if (this.handleKeyCommand(event)) {
    // if we've handled it, don't do anything else?
    return;
  else if (key.isDelete()) {
    this.handleDeletion(event);
    event.preventDefault();
  } else if (key.isEnter()) {
    this.handleNewline(event);
  } else if (key.isPrintable()) {
    // ...
  }

  this.handleExpansion(event);
}
```

## Pass `editor` to key command `check`

#167 adds a `check` function to the key command, but this doesn't receive the editor so cannot conditionally perform the command based on the state of the editor itself.

Eg. to override enter if the editor has content:

```js
editor.registerKeyCommand({
  check(key, editor) {
    return key.isEnter() && !editor.post.isBlank();
  },
  run(editor) {
  }
})
```

## Implement internal key commands using registerKeyCommand

Once the above are done, it would be possible to implement `handleDeletion` and `handleNewLine` etc as commands themselves:

```js
editor.registerKeyCommand({
  check(key) {
    return key.isDelete();
  },
  run(editor) {
    // current deletion behaviour
  }
})
```

However, that raises the issue of what happens if you register a duplicate command (eg to override handleDeletion). 

## Allow prepending commands

Currently `registerKeyCommand` [pushes onto the end of the stack][3] so if you wanted to register a command to override built-in behaviour then it would never be called as the first matching command is run and subsequent ones aren't.

Options here could be to add a flag to `registerKeyCommand`, a named parameter, or a separate method:

```js
editor.registerKeyCommand(command, true) // true to unshift vs push
editor.registerKeyCommand(command, { prepend: true })
editor.prependKeyCommand(command);
```

If commands were named, then we could also do something like:

```js
editor.registerKeyCommand(command, { before: "delete" })
```

... but that starts getting complex and I don't think that's necessary.

[1]:  https://github.com/bustlelabs/content-kit-editor/blob/e64872aca5ee6e59c5a22fc4cd70b17084769a72/src/js/editor/editor.js#L580-L603
[2]: https://github.com/bustlelabs/content-kit-editor/blob/e64872aca5ee6e59c5a22fc4cd70b17084769a72/src/js/editor/editor.js#L608
[3]: https://github.com/bustlelabs/content-kit-editor/blob/e64872aca5ee6e59c5a22fc4cd70b17084769a72/src/js/editor/editor.js#L199

**Comment by bantic** [comment]
@rlivsey Thanks for putting this together.

> Pass editor to key command check

I think that anything related to the editor could also happen in the `run` command. E.g. if the editor is blank make the `run` be a no-op, rather than doing the blankness-check in `check`. Since that seems to handle the same use case I'm not sure if there's a need to pass `editor` to `check`.

> Handle key commands first

Yeah, this makes sense, as does prepending registered key commands. I also think that adding `before`/`after` semantics for the key commands is more than is necessary right now.

If we `registerKeyCommand` to always prepend, then any key commands registered in user-land code would be able to override the internal key commands, which seems correct.

There may be some tricky parts to consider surrounding preventing default behavior. Some of the default behavior we deliberately prevent (newlines, deletes) because it has the potential to cause inconsistent changes to the contentEditable dom. But I think that will still fit with the ideas you describe above.

Regarding the "check" command, what would you think about using a string to describe the key-sequence instead? Like "CTL-A" or "CMD-A". We'd have to define string representations for the important meta characters, but they are fairly small: up, down, left, right, control, alt, command, shift, delete, backspace. This seems like it could make registering key commands feel a little simpler, and avoids exposing the `Key` class. It also keeps the door open for handling multi-key selections that don't map to a single keydown, example: "a-b-c" could be a valid key sequence (in the future).

**Comment by rlivsey** [comment]
> I'm not sure if there's a need to pass editor to check.

The reason I thought about doing things like that in `check` was that `e.preventDefault()` gets called when calling `run`, otherwise we need to only stop the event if `run` is successful.

One of our use-cases in our app is for cursor navigation, where we want to capture `down` and if you're on the last line then the cursor moves to another input in our UI. [Here's an example in the playground](https://github.com/rlivsey/content-kit-playground/blob/master/app/components/my-content-kit-editor/component.js#L46).

If `run` can be a no-op then there should probably be a way of informing the calling code that nothing happened, not to prevent default and to move onto the next matching command (or to the default behaviour).

This could just be as simple as returning `true/false` from `run`, where `false` means "I did nothing, don't cancel the event"? 

> If we registerKeyCommand to always prepend, then any key commands registered in user-land code would be able to override the internal key commands, which seems correct.

That works for me, last registered wins should cover most use-cases.

> what would you think about using a string to describe the key-sequence instead

Provided there was a way of falling through if `run` is a no-op as above, then I think that would work really well.

I've done [something similar](https://gist.github.com/rlivsey/5092e82e9b1d76ea564e) in the past (warning, old school Function.prototype extensions) to support things like `ctrl+enter`, there's also [Mousetrap](https://craig.is/killing/mice) to take inspiration from for more complex commands.

**Comment by rlivsey** [comment]
> There may be some tricky parts to consider surrounding preventing default behavior

Are there any use-cases you can think of where you'd want a command to run but still trigger the default event?

The current behaviour that running a command automatically calls `preventDefault` is fine for all cases I have personally. Could maybe add an option when registering the command in future if the need comes up?

```js
editor.registerKeyCommand({
  str: "CMD+A",
  preventDefault: true,
  run(editor) { }
})
```

Alternatively `run` could take the event so it's the command's job to call `preventDefault`?

**Comment by bantic** [comment]
> Are there any use-cases you can think of where you'd want a command to run but still trigger the default event?

That's a good point. I don't have any particular ones in mind. I was thinking that non-modifier key commands (e.g. just "j") might be ones that wouldn't want their default prevented, although that may not even be true and regardless it's not a use case we've encountered yet. Was probably overthinking that. Adding an option in the future seems like a good plan until/unless there is a solid use case for not preventing the default.
