### ISSUE TITLE
Loading via webpack

### ISSUE THREAD

**Issue by chrishutchinson** [bustlelabs/content-kit-editor#181]
Hey,

I've posted this on Gitter but thought I'd formally log an issue too.

I've not been able to successfully load this library using webpack via `require('content-kit-editor')`, after installing the library via `npm` .

My app is a scaffolded from https://github.com/newtriks/generator-react-webpack, and doesn't have any custom webpack config beyond what that generator provides out of the box.

Any help would be great :smile_cat:

**Comment by mixonic** [comment]
Ah, we must enable CommonJS builds. This is akin to the [changes we made in mobiledoc-dom-renderer](https://github.com/bustlelabs/mobiledoc-dom-renderer/compare/f60bc902bc693ec3c25f4c17c4a110f4041036ee...955d8af4f09b5c81425a68a6b2e9a8deacb1a544).

And you'll end up needing to reference `default`, ala:

```js
let { default: ContentKit } = require('content-kit-editor');
```

I'll aim to publish a the next npm version with CommonJS. Likely 0.5.0.

**Comment by chrishutchinson** [comment]
Awesome thank you @mixonic! Any idea on the timeline for 0.5.0? We're looking to use this in a production tool soon, but need to run the editor through its paces before we can commit to using it!

Having CommonJS support will be part of that.

**Comment by mixonic** [comment]
0.5.0 is waiting on copy/paste stabilizing, I think that is pretty much it. Perhaps today, early next week at the latest.

If the timing is important and you want to lend a hand, the commits I linked above should layout what needs to happen for CommonJS to be included in `dist/` and usable via `main`.

**Comment by mixonic** [comment]
@chrishutchinson care to give this a try today? You should be able to install 0.5.0-beta1 with CommonJS files.

```
npm install --save-dev content-kit-editor@0.5.0-beta1
```

**Comment by mixonic** [comment]
@chrishutchinson 0.5.0 is out now, you should be good to go. Please re-open or let me know if you cannot get this working though!
