### ISSUE TITLE
Paste ignores current selection

### ISSUE THREAD

**Issue by rlivsey** [bustlelabs/content-kit-editor#184]
If there's a selection when you paste, it currently just inserts at the head instead of replacing the existing selection.

![](http://zippy.gfycat.com/RequiredWarlikeKinglet.gif)

**Comment by bantic** [comment]
@rlivsey Good catch, thank you. I'll take a crack at this right now.

**Comment by bantic** [comment]
this fix is released in content-kit-editor 0.4.11 (ember-content-kit also bumped to 0.1.10 to bring in this change)

**Comment by rlivsey** [comment]
Awesome thanks!
