### ISSUE TITLE
Selecting a word then typing over kills the trailing space

### ISSUE THREAD

**Issue by gdub22** [bustlelabs/content-kit-editor#195]
![typing](https://cloud.githubusercontent.com/assets/411908/10762767/bdb549e2-7c9d-11e5-89d1-c4f60dc94483.gif)

**Comment by mixonic** [comment]
Ugh. So it appears that the browser is "correcting" the two spaces before allowing the `input` event to fire. I'm pondering a workaround, but this may just be tied to managing the cursor ourselves.

**Comment by mixonic** [comment]
Failing test in https://github.com/mixonic/content-kit-editor/commit/9dab365015bc8ef3c87a899dc7d1b7d7d27129f5
