### ISSUE TITLE
Placeholder is ignored, editor renders `__BLANK__` when initialised with no mobiledoc

### ISSUE THREAD

**Issue by ErisDS** [bustlelabs/content-kit-editor#35]
Initialising a new editor with no Mobiledoc option results in the editor showing `__BLANK__`:

![](http://puu.sh/jqnGR.png)

How I reproduced:

- on master (58ffbc8) using `broccoli serve` to test the demo
- remove line 264 from `demo/demo.js` (or replace with something like `placeholder: 'my custom placeholder'`)
- visit http://localhost:4200/demo/ and note the `__BLANK__` marker shown in the editor rather than a placeholder.

This was introduced in 0.2.2, in 0.2.1 the placeholder appears.

**Comment by bantic** [comment]
Thanks for reporting this! #127 Changed the way an empty mobiledoc is handled, and placeholders now show up appropriately. The [demo](http://bustlelabs.github.io/content-kit-editor/demo/) has an "Empty mobiledoc" option in the dropdown, showing the placeholder in action.
