### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by dustyjewett** [bustlelabs/content-kit-editor#4]
Hello! We're looking at using a library for content editing in our app, and seriously considering content-kit... but it isn't really packaged for consumption as a lib (specifically, we would want bower/es6). 

What is your intention with the future growth of content-kit / this repository? Should we just fork the repo, remove the node/aws and maintain it ourselves? I've got approximately 1 man month to spend on my project, the main features not currently supported being word/phrase highlighting/tagging, diff-ing versions, MathML, tables, and full test coverage. 

From what I can tell, a large chunk of these will be commands (and additions to the compiler), but some (like highlighting / tagging, which require searching for text) may require larger changes.  Full Test Coverage will also likely require changes.

I'm perfectly comfortable forking and moving forward on this on my own if these things don't align with your roadmap/goals... but if possible, I'd like to consolidate effort.

**Comment by gdub22** [comment]
@dustyjewett thanks for your interest in the project!  
This is still extremely alpha and I wouldn't recommend using it in production in its current state.
The project will be ramping up development this summer which will focus on stability with the current feature set. The src code is currently written with es6 modules and transpiled to globals.  Once things stabilize more, ill release to bower, et al.
