### ISSUE TITLE
first item in `model` serialization is `null` when 2nd item is a list

### ISSUE THREAD

**Issue by bantic** [bustlelabs/content-kit-editor#6]
To reproduce this, delete all contents from the CK editor pane, then create a list with an item. Use arrow keys to move to the first item, hit enter, then up, then delete so that the cursor is now on a line above the list. The model serialization will display `null` for this block.

![image](https://cloud.githubusercontent.com/assets/2023/8341676/726bc152-1a94-11e5-8c5d-139f0a657536.png)

![cc](https://cloud.githubusercontent.com/assets/2023/8341729/d93fbf14-1a94-11e5-99b7-825a5b9f4788.gif)

**Comment by mixonic** [comment]
Now defunct.
