### ISSUE TITLE
Placeholder text does not show

### ISSUE THREAD

**Issue by jacojoubert** [bustlelabs/content-kit-editor#71]
The css for showing the placeholder requires that the main editor have no child nodes. Because an empty `p` tag is now forced via #66 this means the placeholder will never show.

https://github.com/bustlelabs/content-kit-editor/blob/278e02c1c452f67ab916b7f3c5f35bec5f76748c/src/css/editor.less#L22-L23

**Comment by bantic** [comment]
In #127, the forcing of the empty section was removed, and placeholder text now does show up.
