### ISSUE TITLE
Hit enter to put a section after a card

### ISSUE THREAD

**Issue by bantic** [bustlelabs/content-kit-editor#79]
When a card is the final section in a mobiledoc it is difficult to add a section below it (or remove the card) without a target area below for the cursor to go into.

**Comment by bantic** [comment]
There's a spike here that uses a heuristic to determine when the down arrow was pressed in a spot that would have selected a card below it: https://github.com/bustlelabs/content-kit-editor/tree/spike-selectable-cards

**Comment by mixonic** [comment]
Closed in favor of https://github.com/bustlelabs/content-kit-editor/issues/182
