### ISSUE TITLE
Checking for a valid selection in commands should not be needed

### ISSUE THREAD

**Issue by mixonic** [bustlelabs/content-kit-editor#81]
This check: https://github.com/bustlelabs/content-kit-editor/blob/master/src/js/commands/italic.js#L18

should not be required. I was able to trigger the case it protects against by selecting a headline then halfway below but not into the next line.

**Comment by bantic** [comment]
The code referred to here has since been refactored away. Text Format commands no longer need to check if there is a valid selection.
