### ISSUE TITLE
control-K clears section, causes cursor placement errors

### ISSUE THREAD

**Issue by bantic** [bustlelabs/content-kit-editor#96]
On Mac, Chrome:
Hitting control-K at the beginning of a section clears the section and an error appears in the console: "cannot move cursor to section without a marker".

**Comment by bantic** [comment]
Better semantic cursor position detection (via #115) has fixed this problem.

**Comment by mixonic** [comment]
Reopening this, it should be implemented by a keyboard command in content-kit

**Comment by bantic** [comment]
A key command for this was [added in 7774864](https://github.com/bustlelabs/content-kit-editor/blob/7774864980b6944edd755346044ff13f730fa299/src/js/editor/key-commands.js#L48-L57)
